name: Python Package CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: "usmannazirbareet"
      TWINE_PASSWORD: "ec40aff2-f373-42d2-b58f-d7ac728b75dd"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10  # Replace 'x' with the desired Python version

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt  # Replace with your actual requirements file

    # - name: Run tests
    #   run: |
    #     python -m unittest discover tests  # Replace with your test command

  deploy:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: "usmannazirbareet"
      TWINE_PASSWORD: "ec40aff2-f373-42d2-b58f-d7ac728b75dd"
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10  # Replace 'x' with the desired Python version

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt  # Replace with your actual requirements file

    - name: Build and deploy to PyPI
    
      run: |
        python setup.py sdist bdist_wheel
        pip install twine
        twine upload --username $TWINE_USERNAME --password $TWINE_PASSWORD dist/*
      # env:
      #   TWINE_USERNAME: __token__
      #   TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      # run: |
      #   python setup.py sdist bdist_wheel
      #   pip install twine
      #   twine upload dist/*
